dimata:
  service:
    name : CONT
  jwt:
    latest-pk-uri: https://application.account.esemeton.com/
    aud: ${dimata.service.name}
    iss: http://dimata.com/
    service-key:
      secret: hominahominahominahomina=
      version: "1.0"
      exp: 10|minutes

"%dev":
  quarkus:
    log:
      category:
        {"com.dimata.service.general.harisma"}:
          level: DEBUG
    http:
      auth:
        permission:
          maintainer:
            enabled: false

"%test":
  quarkus:
    http:
      auth:
        permission:
          maintainer:
            enabled: false


quarkus:
  log:
    level: INFO
  http:
    port: 8880
    auth:
      policy:
        protect-policy:
          roles-allowed: protect
        admin-policy:
          roles-allowed: admin
        maintainer-policy:
          roles-allowed: maintainer
      permission:
        public:
          paths: /api/v1/public/*
          policy: permit
        protect:
          paths: /api/v1/protect/*
          policy: authenticated
        admin:
          paths: /api/v1/admin/*
          policy: admin-policy
        maintainer:
          paths: /api/v1/maintainer/*
          policy: maintainer-policy
  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3306/project_backend
  hibernate-orm:
    database:
      generation:
        ~: none